name: Prepare `demo' and `deploy` branches

on: workflow_dispatch

jobs:
  prepare-demo-and-deploy-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out `main` branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO }}

      - name: Prepare `demo` branch
        run: |
          git fetch origin demo
          git checkout demo
          git reset --hard origin/main
          git push -f origin demo

      - name: Prepare `deploy` branch
        run: |
          git fetch origin deploy
          git checkout deploy
          git reset --hard origin/main
          git push -f origin deploy
